version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing NestJS CLI and dependencies..."
      - npm install -g @nestjs/cli typescript  
      - npm install  

  build:
    commands:
      - echo "Running tests..."
      - npm run test  
      - echo "Building the NestJS project..."
      - npm run build
      - ls dist/
        
  post_build:
    commands:
      - echo "Zipping the build artifacts..."
      - zip -r backend.zip . -x "node_modules/*" ".git/*" ".aws/*"

artifacts:
  files:
    - backend.zip
    - Procfile 